export const ROLES = ['USER', 'WORKER', 'MANAGER', 'ADMIN'];
export const STATUSES = ['SUBMITTED', 'ANALYZING', 'ASSIGNED', 'AWAITING_ACCEPTANCE', 'ACCEPTED', 'IN_PROGRESS', 'RESOLVED', 'AWAITING_CONFIRMATION', 'CLOSED', 'REOPENED', 'ESCALATED'];
export const PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
